-- =====================================================
-- BILLETERA PERSONAL
-- Estructura inicial de la base de datos PostgreSQL
-- =====================================================

-- Tabla principal de movimientos financieros.
CREATE TABLE IF NOT EXISTS movimientos (
    -- IDENTIFICADOR UNICO DE CADA MOVIMIENTO
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- FECHA EN QUE SE REGISTRO EL MOVIMIENTO
    fecha DATE NOT NULL,
    
    -- SOLO SE PERMITEN INGRESOS O GASTOS
    tipo VARCHAR(10) NOT NULL
        CHECK (tipo IN ('Ingreso', 'Gasto')),

    -- CATEGORIA DEL MOPVIMIENTO
    categoria VARCHAR(100) NOT NULL,

    -- DESCRIPCION OPCIOCIONAL DEL MOVIMIENTO
    descripcion TEXT,

    -- VALOR MONETARIO CON 2 DECIMALES
    monto NUMERIC(12, 2) NOT NULL
        CHECK (monto >= 0)
)